FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["src/FoundFlow.WebApi/FoundFlow.WebApi.csproj", "src/FoundFlow.WebApi/"]
RUN dotnet restore "src/FoundFlow.WebApi/FoundFlow.WebApi.csproj"
COPY . .
WORKDIR "/src/src/FoundFlow.WebApi"
RUN dotnet build "FoundFlow.WebApi.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "FoundFlow.WebApi.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "FoundFlow.WebApi.dll"]