//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoundFlow.Shared.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FoundFlow.Shared.Messages.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A categoria já está cadastrada..
        /// </summary>
        public static string CategoriesCategorieIsRegisteredMessage {
            get {
                return ResourceManager.GetString("CategoriesCategorieIsRegisteredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe uma categoria com esse nome..
        /// </summary>
        public static string CategoriesCategorieIsRegisteredWithNameMessage {
            get {
                return ResourceManager.GetString("CategoriesCategorieIsRegisteredWithNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A categoria não foi encontrada..
        /// </summary>
        public static string CategoriesCategorieNotFoundMessage {
            get {
                return ResourceManager.GetString("CategoriesCategorieNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A cor deve estar no formato hexadecimal (ex: #FFFFFF)..
        /// </summary>
        public static string CategoriesValidationColorFormatMessage {
            get {
                return ResourceManager.GetString("CategoriesValidationColorFormatMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A cor é obrigatória..
        /// </summary>
        public static string CategoriesValidationColorRequiredMessage {
            get {
                return ResourceManager.GetString("CategoriesValidationColorRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Id de categoria precisa ser um GUID..
        /// </summary>
        public static string CategoriesValidationIdCategorieInvalidMessage {
            get {
                return ResourceManager.GetString("CategoriesValidationIdCategorieInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Id da categoria é obrigatório..
        /// </summary>
        public static string CategoriesValidationIdCategorieRequireMessage {
            get {
                return ResourceManager.GetString("CategoriesValidationIdCategorieRequireMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome da categoria precisa ter no mínimo {MinLength} caracter(es)..
        /// </summary>
        public static string CategoriesValidationNameMinimumLengthMessage {
            get {
                return ResourceManager.GetString("CategoriesValidationNameMinimumLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome da categoria é inválido..
        /// </summary>
        public static string CategoriesValidationRequiredNameMessage {
            get {
                return ResourceManager.GetString("CategoriesValidationRequiredNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Id do usuário é obrigatório..
        /// </summary>
        public static string CategoriesValidationUserIdMessage {
            get {
                return ResourceManager.GetString("CategoriesValidationUserIdMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível salvar o(s) registro(s) no banco de dados, fale com um administrador..
        /// </summary>
        public static string DatabaseSaveErrorMessage {
            get {
                return ResourceManager.GetString("DatabaseSaveErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Bearer token não foi enviado corretamente..
        /// </summary>
        public static string TokenJwtNotSentCorrectlyMessage {
            get {
                return ResourceManager.GetString("TokenJwtNotSentCorrectlyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A transação não foi encontrada..
        /// </summary>
        public static string TransactionsTransactionNotFoundMessage {
            get {
                return ResourceManager.GetString("TransactionsTransactionNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor da transação é de no mínimo R$ {MinLength}..
        /// </summary>
        public static string TransactionsValidationAmountRequireMessage {
            get {
                return ResourceManager.GetString("TransactionsValidationAmountRequireMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Id da transação é obrigatório..
        /// </summary>
        public static string TransactionsValidationIdTransactionRequireMessage {
            get {
                return ResourceManager.GetString("TransactionsValidationIdTransactionRequireMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Titulo da transação é obrigatório..
        /// </summary>
        public static string TransactionsValidationTitleRequireMessage {
            get {
                return ResourceManager.GetString("TransactionsValidationTitleRequireMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tipo de transição não está no formato correto..
        /// </summary>
        public static string TransactionsValidationTransactionTypeRequireMessage {
            get {
                return ResourceManager.GetString("TransactionsValidationTransactionTypeRequireMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data de pagamento/deposito precisa ser uma data válida..
        /// </summary>
        public static string TransactionValidationPaymentDateFormatMessage {
            get {
                return ResourceManager.GetString("TransactionValidationPaymentDateFormatMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data de pagamento/deposito é obrigatória..
        /// </summary>
        public static string TransactionValidationPaymentDateRequireMessage {
            get {
                return ResourceManager.GetString("TransactionValidationPaymentDateRequireMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O status de pagamento não está no formato correto..
        /// </summary>
        public static string TransactionValidationPaymentStatusRequireMessage {
            get {
                return ResourceManager.GetString("TransactionValidationPaymentStatusRequireMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O usuário está temporáriamente bloqueado..
        /// </summary>
        public static string UserLoginAccountTemporaryBlockedMessage {
            get {
                return ResourceManager.GetString("UserLoginAccountTemporaryBlockedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O usuário não foi encontrado..
        /// </summary>
        public static string UserNotFoundMessage {
            get {
                return ResourceManager.GetString("UserNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O email já foi cadastrado..
        /// </summary>
        public static string UsersEmailIsRegisteredMessage {
            get {
                return ResourceManager.GetString("UsersEmailIsRegisteredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O usuário está bloqueado na plataforma..
        /// </summary>
        public static string UsersLoginAccountIsBlockedMessage {
            get {
                return ResourceManager.GetString("UsersLoginAccountIsBlockedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario ou senha inválido..
        /// </summary>
        public static string UsersLoginIncorrectMessage {
            get {
                return ResourceManager.GetString("UsersLoginIncorrectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O usuário não foi encontrado..
        /// </summary>
        public static string UsersNotFoundMessage {
            get {
                return ResourceManager.GetString("UsersNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A confirmação de senha e a senha precisam ser iguais..
        /// </summary>
        public static string UsersValidationConfirmPasswordMessage {
            get {
                return ResourceManager.GetString("UsersValidationConfirmPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O email informado está incorreto..
        /// </summary>
        public static string UsersValidationEmailMessage {
            get {
                return ResourceManager.GetString("UsersValidationEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha precisa ter no mínimo {MinLength} caracter(es)..
        /// </summary>
        public static string UsersValidationMinLengthPasswordMessage {
            get {
                return ResourceManager.GetString("UsersValidationMinLengthPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do usuário deve conter ao menos {MinLength} caracter(es)..
        /// </summary>
        public static string UsersValidationMinLengthUserNameMessage {
            get {
                return ResourceManager.GetString("UsersValidationMinLengthUserNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Notificação é obrigatório..
        /// </summary>
        public static string UsersValidationNotificationMessage {
            get {
                return ResourceManager.GetString("UsersValidationNotificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha preicsa conter ao menos 1 letra maiúscula, 1 letra mínuscula e 1 número..
        /// </summary>
        public static string UsersValidationPasswordComplexityMessage {
            get {
                return ResourceManager.GetString("UsersValidationPasswordComplexityMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha é inválida..
        /// </summary>
        public static string UsersValidationPasswordMessage {
            get {
                return ResourceManager.GetString("UsersValidationPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do usuário é inválido..
        /// </summary>
        public static string UsersValidationUserNameMessage {
            get {
                return ResourceManager.GetString("UsersValidationUserNameMessage", resourceCulture);
            }
        }
    }
}
