//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoundFlow.Shared.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FoundFlow.Shared.Messages.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível salvar o(s) registro(s) no banco de dados, fale com um administrador..
        /// </summary>
        public static string DatabaseSaveError {
            get {
                return ResourceManager.GetString("DatabaseSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O usuário está temporáriamente bloqueado..
        /// </summary>
        public static string UserLoginAccountTemporaryBlocked {
            get {
                return ResourceManager.GetString("UserLoginAccountTemporaryBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O email já foi cadastrado..
        /// </summary>
        public static string UsersCreateEmailIsRegistered {
            get {
                return ResourceManager.GetString("UsersCreateEmailIsRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A confirmação de senha e a senha precisam ser iguais..
        /// </summary>
        public static string UsersCreateValidationConfirmPasswordMessage {
            get {
                return ResourceManager.GetString("UsersCreateValidationConfirmPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha precisa ter no mínimo {MinLength} caracter(es)..
        /// </summary>
        public static string UsersCreateValidationMinLengthPasswordMessage {
            get {
                return ResourceManager.GetString("UsersCreateValidationMinLengthPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do usuário deve conter ao menos {MinLength} caracter(es)..
        /// </summary>
        public static string UsersCreateValidationMinLengthUserNameMessage {
            get {
                return ResourceManager.GetString("UsersCreateValidationMinLengthUserNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Notificação é obrigatório..
        /// </summary>
        public static string UsersCreateValidationNotificationMessage {
            get {
                return ResourceManager.GetString("UsersCreateValidationNotificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha preicsa conter ao menos 1 letra maiúscula, 1 letra mínuscula e 1 número..
        /// </summary>
        public static string UsersCreateValidationPasswordComplexityMessage {
            get {
                return ResourceManager.GetString("UsersCreateValidationPasswordComplexityMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha é inválida..
        /// </summary>
        public static string UsersCreateValidationPasswordMessage {
            get {
                return ResourceManager.GetString("UsersCreateValidationPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do usuário é inválido..
        /// </summary>
        public static string UsersCreateValidationUserNameMessage {
            get {
                return ResourceManager.GetString("UsersCreateValidationUserNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O usuário está bloqueado na plataforma..
        /// </summary>
        public static string UsersLoginAccountIsBlocked {
            get {
                return ResourceManager.GetString("UsersLoginAccountIsBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario ou senha inválido..
        /// </summary>
        public static string UsersLoginIncorrect {
            get {
                return ResourceManager.GetString("UsersLoginIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O email informado está incorreto..
        /// </summary>
        public static string UsersLoginValidationEmailMessage {
            get {
                return ResourceManager.GetString("UsersLoginValidationEmailMessage", resourceCulture);
            }
        }
    }
}
