version: '3.9'

services:
  postgres:
    container_name: found-flow-db
    image: postgres:16
    environment:
      POSTGRES_USER: master
      POSTGRES_PASSWORD: S3cret
      POSTGRES_DB: found_flow_db
      PGDATA: /data/postgres
    volumes:
       - database:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - database
    restart: unless-stopped
  mongodb:
    image: mongo
    container_name: found-flow-cache
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: flowmagicuser
      MONGO_INITDB_ROOT_PASSWORD: F0und#Fl0wPaxx
    volumes:
      - database:/data/db
    networks:
      - database
networks:
  database:
    driver: bridge

volumes:
    database:
